name: docInHand
description: A new Flutter project.

publish_to: 'AndersonL95' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  localization: ^2.1.1
  cupertino_icons: ^1.0.8
  http: 1.3.0
  shared_preferences: 2.5.3
  toastification: ^3.0.2
  provider: ^6.1.4
  flutter_pdfview: 1.4.0
  path_provider: ^2.1.5
  printing: 5.14.2
  flutter_localization: 0.3.2
  intl: 0.20.2
  mask_text_input_formatter: ^2.9.0
  input_quantity: 2.5.1
  file_picker: 9.2.2
  image_picker: ^1.1.2
  fl_chart: 0.70.2
  file_saver: ^0.2.14
  currency_text_input_formatter: 2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0


flutter:

  
  uses-material-design: true
  assets:
  - Assets/logo/
  - Assets/images/
  - Assets/gif/
  